openapi: '3.0.3'
info:
  title: Describe OpenVPN tunnel schema
  version: 0.1.0
components:
  schemas:
    OpenVPN:
      type: object
      properties:
        source:
          type: string
          format: ipv4
        destination:
          type: string
          format: ipv4
        address:
          type: string
          format: ipv4
        remote:
          type: string
          format: ipv4
        mode:
          type: string
          enum: [site-to-site, client, server]
      required:
        - souce
        - destination
        - address
        - remote
        - mode
paths:
  /interface/openvpn/{name}:
    put:
      summary: Create openvpn instance
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: OpenVPN instance name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenVPN'
      responses:
        '200':
          description: Success
    get:
      summary: Get openvpn attributes by name
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: OpenVPN instance name
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenVPN'
        '404':
          description: No such openvpn interface
